[username]
format = " [╭─$user](bold blue)@"
show_always = true

[directory]
style = "red bold"
truncate_to_repo = false
truncation_length = 3

[character]
success_symbol = " [╰─λ](bold blue)"
error_symbol = " [×](bold red)"

[git_branch]
format = "on [$branch]($style) "
style = "green"

[nodejs]
disabled = true

[golang]
disabled = true

[python]
disabled = true
